#!/usr/bin/env bash

#
# Neon
# Copyright (C)  2017  Nenad Radulovic
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# This script will generate the ``doxyfile_version`` file which defines the
# current git version.

set -e
set -u

. functions

cat > ../documentation/doxyfile_version << EOF
#
# This file is automatically generated by ${0} script.
# Do not edit it manually since any change will be overwriten!
#
PROJECT_NUMBER = "$(get_git_version)"
EOF

doxygen ../documentation/doxyfile
